services:
  nestapp:
    container_name: nestapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:3000
    volumes:
      - .:/usr/src/app
    command: npm run test:e2e
    environment:
      - API_PORT=${API_PORT}
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
